version: '3.8'

services:
  db:
    image: postgres:15
    container_name: vexylo_db
    env_file:
      - .env
    ports:
      - "2050:5432"
    labels:
      - "vexylo.project=true"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: vexylo_pgadmin
    env_file:
      - .env
    ports:
      - "2070:80"
    labels:
      - "vexylo.project=true"
    depends_on:
      - db
    restart: unless-stopped

  api:
    build: ./backend-api
    container_name: vexylo_api
    ports:
      - "2060:2060"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}
    volumes:
      - ./backend-api:/app
    labels:
      - "vexylo.project=true"
    depends_on:
      - db
    restart: unless-stopped
    # Para ler os processos do host (Windows/Linux local), PID namespace do host e privileges:
    pid: "host"
    privileged: true

  docker-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: vexylo_docker_proxy
    environment:
      - CONTAINERS=1
      - POST=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "vexylo.project=true"
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    container_name: vexylo_portainer
    command: -H tcp://docker-proxy:2375
    ports:
      - "2080:9000"
    depends_on:
      - docker-proxy
    labels:
      - "vexylo.project=true"
    restart: unless-stopped

volumes:
  postgres_data: