version: '3.8'

services:
  # 1. BASE DE DADOS (Postgres)
  db:
    image: postgres:15-alpine
    container_name: superdashboard-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: superdashboard
    ports:
      - "2000:5432" # Acedes à DB por fora via porta 2000
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d superdashboard"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. A TUA API (FastAPI)
  api:
    build: ./backend-api
    container_name: superdashboard-api
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:supersecretpassword@db:5432/superdashboard
      PORT: 2001
    ports:
      - "2001:2001" # O teu PC acede pela 2001 -> vai para a 2001 interna da API
    depends_on:
      db:
        condition: service_healthy

  # 3. UI DA BASE DE DADOS (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: superdashboard-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jarvis.com
      PGADMIN_DEFAULT_PASSWORD: supersecretpassword
    ports:
      - "5050:80" # Vais abrir a interface gráfica da DB na porta 5050
    depends_on:
      - db

  # 4. GESTOR DE CONTAINERS (Portainer)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: superdashboard-portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000" # Vais controlar o Docker todo na porta 9000

volumes:
  pgdata:
  portainer_data: